# Generated by Django 2.0.9 on 2018-12-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
